# Generated by Django 3.1.2 on 2020-10-24 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistemas', '0005_auto_20201024_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('legajo', models.IntegerField()),
                ('mail', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sistemas.sistema')),
            ],
            options={
                'db_table': 'medicos',
            },
        ),
        migrations.CreateModel(
            name='JefeSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('legajo', models.IntegerField()),
                ('mail', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('sistema', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='sistemas.sistema')),
            ],
            options={
                'db_table': 'jefes',
            },
        ),
    ]
