# Generated by Django 3.1.2 on 2020-10-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jefesistema',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='id',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='legajo',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='password',
        ),
        migrations.RemoveField(
            model_name='jefesistema',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='legajo',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='password',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='usuario',
        ),
        migrations.CreateModel(
            name='TrabajadorHospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('legajo', models.IntegerField()),
                ('mail', models.CharField(max_length=255)),
                ('usuario', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_medicos.trabajadorhospital_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.AddField(
            model_name='jefesistema',
            name='trabajadorhospital_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medicos.trabajadorhospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medico',
            name='trabajadorhospital_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='medicos.trabajadorhospital'),
            preserve_default=False,
        ),
    ]
