# Generated by Django 3.1.2 on 2020-10-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('antecedentes_personales', models.TextField()),
                ('alta', models.CharField(choices=[('E', 'epidemiologica'), ('C', 'curado')], max_length=1)),
                ('obito', models.BooleanField(default=False)),
                ('nombre_y_apellido', models.CharField(max_length=255)),
                ('fecha_nacimiento', models.DateField()),
                ('mail', models.CharField(max_length=255)),
                ('obra_social', models.TextField()),
                ('dni', models.IntegerField()),
                ('domicilio', models.TextField()),
                ('nombre_contacto', models.CharField(max_length=255)),
                ('apellido_contacto', models.CharField(max_length=255)),
                ('telefono', models.IntegerField()),
                ('parentesco', models.TextField()),
            ],
            options={
                'db_table': 'pacientes',
            },
        ),
    ]
