# Generated by Django 3.1.2 on 2020-10-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='parentesco',
            new_name='parentesco_contacto',
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_contacto',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
