# Generated by Django 3.1.2 on 2020-10-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_auto_20201022_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono_contacto',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
