# Generated by Django 3.1.2 on 2020-10-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
        ('pacientes', '0005_auto_20201022_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicos',
            field=models.ManyToManyField(to='medicos.Medico'),
        ),
    ]
