# Generated by Django 3.1.2 on 2020-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20201029_1030'),
        ('pacientes', '0006_paciente_medicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medicos',
            field=models.ManyToManyField(to='medicos.TrabajadorHospital'),
        ),
    ]
