# Generated by Django 3.1.2 on 2020-11-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20201029_1030'),
        ('pacientes', '0009_auto_20201029_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medicos',
            field=models.ManyToManyField(blank=True, null=True, to='medicos.TrabajadorHospital'),
        ),
    ]
