# Generated by Django 3.1.2 on 2020-11-04 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_auto_20201029_1030'),
        ('pacientes', '0010_auto_20201104_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='medicos',
            field=models.ManyToManyField(to='medicos.TrabajadorHospital'),
        ),
    ]
