# Generated by Django 3.1.2 on 2020-11-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0011_auto_20201104_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_sintomas', models.DateField()),
                ('fecha_diagnostico', models.DateField()),
                ('enfermedad_actual', models.TextField()),
                ('descripcion', models.TextField()),
                ('fecha_internacion', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('fecha_obito', models.DateField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
            options={
                'db_table': 'internaciones',
            },
        ),
    ]
