# Generated by Django 3.1.2 on 2020-11-06 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0012_internacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacion',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='enfermedad_actual',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='fecha_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='fecha_inicio_sintomas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='internacion',
            name='fecha_internacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
