# Generated by Django 3.1.2 on 2020-11-13 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_auto_20201106_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internacion',
            name='fecha_internacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='alta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
