# Generated by Django 3.1.2 on 2020-11-13 17:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evolucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_carga', models.DateField(default=django.utils.timezone.now)),
                ('hora_carga', models.TimeField(default=django.utils.timezone.now)),
                ('temperatura', models.DecimalField(decimal_places=1, max_digits=5)),
                ('ta_sistolica', models.IntegerField()),
                ('ta_diastolica', models.IntegerField()),
                ('frecuencia_cardiaca', models.IntegerField()),
                ('frecuencia_respiratoria', models.IntegerField()),
                ('mecanica_ventilatoria', models.CharField(max_length=255)),
                ('requiere_o2_suplementario', models.BooleanField(default=False)),
                ('canula_nasal', models.IntegerField(blank=True, null=True)),
                ('mascara_con_reservorio', models.IntegerField(blank=True, null=True)),
                ('saturacion_o2', models.IntegerField(blank=True, null=True)),
                ('pafi', models.BooleanField(default=False)),
                ('pafi_valor', models.IntegerField()),
                ('prono_vigil', models.BooleanField(default=False)),
                ('tos', models.BooleanField(default=False)),
                ('disnea', models.IntegerField()),
                ('estabilidad_respiratoria', models.BooleanField(default=False)),
                ('somnolencia', models.BooleanField(default=False)),
                ('anosmia', models.BooleanField(default=False)),
                ('disgeusia', models.BooleanField(default=False)),
                ('rx_tx', models.BooleanField(default=False)),
                ('tipo_rx_tx', models.CharField(max_length=255)),
                ('descripcion_patologico_rx_tx', models.TextField()),
                ('tac_torax', models.BooleanField(default=False)),
                ('tipo_tac_torax', models.CharField(max_length=255)),
                ('descripcion_patologico_tac_torax', models.TextField()),
                ('ecg', models.BooleanField(default=False)),
                ('tipo_ecg', models.CharField(max_length=255)),
                ('descripcion_patologico_ecg', models.TextField()),
                ('pcr_covid', models.BooleanField(default=False)),
                ('tipo_pcr_covid', models.CharField(max_length=255)),
                ('descripcion_pcr_covid', models.TextField()),
                ('observacion', models.TextField()),
                ('arm', models.BooleanField(default=False)),
                ('descripcion_arm', models.TextField()),
                ('traqueostomia', models.BooleanField(default=False)),
                ('vasopresores', models.BooleanField(default=False)),
                ('descripcion_vasopresores', models.TextField()),
            ],
        ),
    ]
