# Generated by Django 3.1.2 on 2020-11-15 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20201113_1424'),
        ('evoluciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evolucion',
            name='internacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pacientes.internacion'),
            preserve_default=False,
        ),
    ]
