# Generated by Django 3.1.2 on 2020-12-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reglas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracionregla',
            name='key',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='configuracionregla',
            name='value',
            field=models.CharField(max_length=255),
        ),
    ]
