# Generated by Django 3.1.2 on 2020-12-10 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20201113_1424'),
        ('reglas', '0002_auto_20201202_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('condicion', models.CharField(blank=True, max_length=255, null=True)),
                ('vista', models.BooleanField(default=False)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='pacientes.paciente')),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
    ]
