# Generated by Django 3.1.2 on 2020-10-24 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0005_auto_20201022_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('camas_infinitas', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sistemas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemas.sala')),
            ],
        ),
    ]
