# Generated by Django 3.1.2 on 2020-10-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cama',
            table='camas',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='salas',
        ),
    ]
