# Generated by Django 3.1.2 on 2020-10-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0005_auto_20201022_1816'),
        ('sistemas', '0003_auto_20201023_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cama',
            name='paciente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pacientes.paciente'),
        ),
    ]
