# Generated by Django 3.1.2 on 2020-11-07 05:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0005_auto_20201024_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioSistema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateField(default=django.utils.timezone.now)),
                ('sistema_destino', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sistema_destino', to='sistemas.sistema')),
                ('sistema_origen', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sistema_origen', to='sistemas.sistema')),
            ],
        ),
    ]
