# Generated by Django 3.1.2 on 2020-11-08 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemas', '0007_cambiosistema_paciente'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cambiosistema',
            table='cambio_sistema',
        ),
    ]
