# Generated by Django 3.1.2 on 2020-11-13 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0013_auto_20201106_0011'),
        ('sistemas', '0008_auto_20201107_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cambiosistema',
            name='paciente',
        ),
        migrations.AddField(
            model_name='cambiosistema',
            name='internacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internacion', to='pacientes.internacion'),
            preserve_default=False,
        ),
    ]
