# Generated by Django 3.1.2 on 2020-11-17 20:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0014_auto_20201113_1424'),
        ('sistemas', '0009_auto_20201113_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiosistema',
            name='hora_cambio',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cambiosistema',
            name='internacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambio_de_sistema', to='pacientes.internacion'),
        ),
    ]
